apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Chart.Name }}
    image-tag: {{ .Values.deployment.image.tag }}
  name: {{ .Chart.Name }}
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
        deployment: {{ .Chart.Name }}
    spec:
      automountServiceAccountToken: false
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.deployment.image.artifact }}:{{ .Values.deployment.image.tag }}"
          envFrom:
            - configMapRef:
                name: {{ .Chart.Name }}-configmap
          command: [ "/bin/sh" ]
          args: [ "-c", "ls -l /otel && chmod 755 /otel/elastic-otel-javaagent.jar && java -javaagent:/otel/elastic-otel-javaagent.jar -jar /simpl-stubs.jar" ]
          env:
            - name: OTEL_SERVICE_NAME
              value: {{ .Chart.Name }}
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: {{ .Values.deployment.otel.endpoint }}
            - name: OTEL_LOGS_EXPORTER
              value: "none"
          resources:
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
          imagePullPolicy: {{ .Values.deployment.image.pullPolicy }}
          ports:
            - containerPort: 8080
              protocol: TCP
          readinessProbe:
            httpGet:
              path: {{ .Values.probe.endpoint }}
              scheme: {{ .Values.probe.scheme }}
              port:  {{ .Values.probe.port }}
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: {{ .Values.probe.endpoint }}
              scheme: {{ .Values.probe.scheme }}
              port:  {{ .Values.probe.port }}
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
          startupProbe:
            failureThreshold: 60
            httpGet:
              path: {{ .Values.probe.endpoint }}
              scheme: {{ .Values.probe.scheme }}
              port:  {{ .Values.probe.port }}
            periodSeconds: 10
