kafkaEndpoint: KAFKA_ENDPOINT_PLACEHOLDER
giteaUrl: GITEA_URL_PLACEHOLDER
vaultServer: VAULT_SERVER_PLACEHOLDER

secrets:
  kafka:
    username: KAFKA_USERNAME_PLACEHOLDER
    password: KAFKA_PASSWORD_PLACEHOLDER
  gitea:
    username: GITEA_USERNAME_PLACEHOLDER
    password: GITEA_PASSWORD_PLACEHOLDER
