apiVersion: beat.k8s.elastic.co/v1beta1
kind: Beat
metadata:
  name: filebeat
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  image: {{ .Values.filebeat.image }}:{{ default .Values.elasticVersion  .Values.filebeat.imageTag }}
  version: {{ .Values.elasticVersion }}
  type: filebeat
  daemonSet:
    podTemplate:
      spec:
        serviceAccountName: filebeat-account
        automountServiceAccountToken: true
        terminationGracePeriodSeconds: 30
        dnsPolicy: ClusterFirstWithHostNet
        hostNetwork: true # Allows to provide richer host metadata
        containers:
        - name: filebeat
          {{- with .Values.filebeat.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          command: ['sh', '-c', 'exec /usr/share/filebeat/filebeat -e -c /usr/share/filebeat/filebeat.yml']
          securityContext:
            runAsUser: 0
            # If using Red Hat OpenShift uncomment this:
            #privileged: true
          volumeMounts:
          - name: varlogcontainers
            mountPath: /var/log/containers
          - name: varlogpods
            mountPath: /var/log/pods
          - name: varlibdockercontainers
            mountPath: /var/lib/docker/containers
          - mountPath: /usr/share/filebeat/filebeat.yml
            subPath: filebeat.yml
            name: config
          - mountPath: /usr/share/filebeat/certs
            name: filebeat-certs
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: ELASTIC_ELASTICSEARCH_ES_HOSTS
              value: 'https://{{ .Release.Name }}-elasticsearch-es-http.{{ .Release.Namespace }}.svc:9200'
            - name: LOGSTASH_HOSTS
              value: 'logstash-{{ .Values.logstash.beats.pipelines_group_name }}-ls-api.{{ .Values.mainNamespace }}.svc.cluster.local:5044'
            - name: MONITORED_NAMESPACE
              value: '{{ .Release.Namespace }}'
        volumes:
        - name: varlogcontainers
          hostPath:
            path: /var/log/containers
        - name: varlogpods
          hostPath:
            path: /var/log/pods
        - name: varlibdockercontainers
          hostPath:
            path: /var/lib/docker/containers
        - name: config
          configMap:
            name: filebeat-config
            defaultMode: 0600
        - name: filebeat-certs
          secret:
            secretName: filebeat-certs-secret-{{ .Release.Namespace }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-config
data:
  filebeat.yml: |
    {{ printf "%s\n%s" .Values.filebeat.input (tpl .Values.filebeat.output $ ) | nindent 6 }}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: filebeat-certificate-{{ .Release.Namespace }}
spec:
  secretName: filebeat-certs-secret-{{ .Release.Namespace }}
  duration: {{ .Values.filebeat.cert.duration }}
  renewBefore: {{ .Values.filebeat.cert.renewBefore }}
  commonName: {{ template "filebeat.dns" . }}
  dnsNames:
    - "{{ template "filebeat.dns" . }}"
  issuerRef:
    name: elk-clusterissuer-{{ .Values.mainNamespace }}
    #name: {{ .Values.clusterIssuer_internal }}
    kind: ClusterIssuer
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: filebeat-role-{{ .Release.Namespace }}
rules:
- apiGroups: [""] # "" indicates the core API group
  resources:
  - namespaces
  - pods
  - nodes
  verbs:
  - get
  - watch
  - list
- apiGroups: ["apps"]
  resources:
  - replicasets
  verbs:
  - get
  - list
  - watch
- apiGroups: ["batch"]
  resources:
  - jobs
  verbs:
  - get
  - list
  - watch
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: filebeat-account
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: filebeat-rolebinding-{{ .Release.Namespace }}
subjects:
- kind: ServiceAccount
  name: filebeat-account
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: filebeat-role-{{ .Release.Namespace }}
  apiGroup: rbac.authorization.k8s.io
---