{{- if eq .Values.namespaceTag .Values.mainNamespace }}
apiVersion: logstash.k8s.elastic.co/v1alpha1
kind: Logstash
metadata:
  name: logstash-beats
  labels:
    app: logstash
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  image: {{ .Values.logstash.image }}:{{ default .Values.elasticVersion  .Values.logstash.imageTag }}
  version: {{ .Values.elasticVersion }}
  {{- if eq .Values.deploy_minimal_stack true }}
  count: {{ .Values.logstash.minimal_stack_count_beats }}
  {{- else }}
  count: {{ .Values.logstash.count_beats }}
  {{- end }}
  elasticsearchRefs:
  - name: {{ .Release.Name }}-elasticsearch
    clusterName: {{ .Release.Name }}-elasticsearch
  monitoring:
    logs:
      elasticsearchRefs:
        - name: {{ .Release.Name }}-elasticsearch
    metrics:
      elasticsearchRefs:
        - name: {{ .Release.Name }}-elasticsearch
  volumeClaimTemplates:
    - metadata:
        name: logstash-data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            {{- if eq .Values.deploy_minimal_stack true }}
            storage: {{ .Values.logstash.minimal_stack_diskSpace }}
            {{- else }}
            storage: {{ .Values.logstash.diskSpace }}
            {{- end }}
        storageClassName: {{ .Values.logstash.storageClassName }}
  services: 
{{- range $index :=  until (.Values.logstash.count_beats |int ) -}}
{{- printf "\n"}}  
    - name: beats-{{$index}}
      service:
        spec:
          ports:
          - port: 5044 
            name: {{ $.Values.logstash.beats.pipelines_group_name }}
            protocol: TCP
          selector:
            statefulset.kubernetes.io/pod-name: logstash-beats-ls-{{$index}}
{{- end}}
  #config:
    #monitoring.enabled: false
  podTemplate:
    metadata:
      labels:
        stack-namespace: {{ .Release.Namespace }} 
    spec:
      {{ if eq .Values.loadSampleBusinessLogs true }}
      initContainers:
        - name: git-clone
          image: alpine/git
          args:
            - clone
            - --single-branch
            - --branch
            - {{ .Values.kibana.dashboardsBranch }}
            - https://code.europa.eu/simpl/simpl-open/development/monitoring/eck-monitoring.git
            - /mnt/ilm
          volumeMounts:
            - name: repo
              mountPath: /mnt/ilm
      {{ end }}
      securityContext:
        runAsUser: 1000
        fsGroup: 1000    
      containers:
      - name: logstash

        {{- if eq .Values.deploy_minimal_stack true }}
        {{- with .Values.logstash.minimal_stack_resources }}
        resources:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{ else }}
        {{- with .Values.logstash.resources }}
        resources:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- end }}

        volumeMounts:
        {{- range .Values.logstash.beats.pipelines }}
        - name: pipeline-config-{{- .name }}
          mountPath: /app/elastic/logstash/config/pipelines/{{- .name -}}.config
          subPath: {{ .name -}}.config
        {{- end }}
        - name: es-certs
          mountPath: /usr/share/logstash/config/certs
        - name: certs-logstash
          mountPath: /usr/share/logstash/certs-logstash
        - name: repo
          mountPath: /mnt/ilm/
        env:
        {{- if eq .Values.deploy_minimal_stack true }}
          - name: MINIMAL_STACK
            value: "true"
          - name: STACK_VERSION
            value: {{ .Values.elasticVersion }}
        {{ end  }}
          - name: LS_JAVA_OPTS
            {{- if eq .Values.deploy_minimal_stack true }}
            {{- $memoryStr :=regexReplaceAllLiteral "[a-zA-Z]?" .Values.logstash.minimal_stack_resources.limits.memory "" }}
            {{- $memory := int $memoryStr }}
            value: "-Xms{{ div $memory 2 }}g -Xmx{{ div $memory 2 }}g"
            {{- else }}
            {{- $memoryStr :=regexReplaceAllLiteral "[a-zA-Z]?" .Values.logstash.resources.limits.memory "" }}
            {{- $memory := int $memoryStr }}
            value: "-Xms{{ div $memory 2 }}g -Xmx{{ div $memory 2 }}g"
            {{- end }}
          - name: LOGSTASH_USER
            valueFrom:
              secretKeyRef:
                name: logstash-writer-secret
                key: username
          - name: LOGSTASH_PASSWORD
            valueFrom:
              secretKeyRef:
                name: logstash-writer-secret
                key: password
          # - name: MONITORING_USER
          #   valueFrom:
          #     secretKeyRef:
          #       name: user-monitoring-secret
          #       key: username
          # - name: MONITORING_PASSWORD
          #   valueFrom:
          #     secretKeyRef:
          #       name: user-monitoring-secret
          #       key: password  
          - name: ELASTIC_ELASTICSEARCH_ES_HOSTS
            value: 'https://{{ .Release.Name }}-elasticsearch-es-http.{{ .Release.Namespace }}.svc:9200'
          - name: ELASTICSEARCH_SSL_CERTIFICATE_VERIFICATION
            value: "true"
          - name: ELASTICSEARCH_SSL_CA_PATH
            value: "/usr/share/logstash/config/certs/ca.crt"
      - name: filebeat
        {{- with .Values.logstash.resources_filebeat }}
        resources:
          {{- toYaml . | nindent 10 }}
        {{- end }}
      - name: metricbeat
        {{- with .Values.logstash.resources_metricbeat }}
        resources:
          {{- toYaml . | nindent 10 }}
        {{- end }}
      volumes:
      {{- range .Values.logstash.beats.pipelines }}
      - name: pipeline-config-{{- .name }}
        configMap:
          name: logstash-{{- $.Values.logstash.beats.pipelines_group_name -}}-{{- .name -}}-config
          defaultMode: 511
      {{- end }}
      - name: es-certs
        secret:
          secretName: {{ .Release.Name }}-elasticsearch-http-cert-secret-internal
      - name: certs-logstash
        secret:
          secretName: logstash-secret-{{ .Values.logstash.beats.pipelines_group_name }}
      - name: repo
        emptyDir: {}
  pipelines:
  {{- range .Values.logstash.beats.pipelines }}
  - pipeline.id: {{ .name }}
    path.config: "{{ default $.Values.logstash.pipeline_defaults.config_path .config_path }}/{{ .name }}.config"
    pipeline.workers: {{ default $.Values.logstash.pipeline_defaults.workers .pipeline_workers }}
    pipeline.batch.size: {{ default $.Values.logstash.pipeline_defaults.batch_size .pipeline_batch_size }}
  {{- end }}
---
{{- range .Values.logstash.beats.pipelines }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-{{ $.Values.logstash.beats.pipelines_group_name }}-{{ .name }}-config
data:
  {{ .name }}.config: |
    input {
    {{- tpl .input $ | nindent 4 }}
    {{- if eq $.Values.loadSampleBusinessLogs true }}
      file {
        id => "business_sample_log"
        path => [ "/mnt/ilm/log_samples/business/business.log"]
        add_field => { "[kubernetes][container][name]" => "tier1-gateway" }
        tags => [ "business_sample_log" ]
        start_position => "beginning"
      }
    {{- end }}
    }
    {{- tpl .filter $ | nindent 4 }}
    {{- tpl .output $ | nindent 4 }}
---
{{- end }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: logstash-api-{{ .Values.logstash.beats.pipelines_group_name }}
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: 50m
    external-dns.alpha.kubernetes.io/hostname: "{{ template "logstash.dns" . }},{{- include "logstash.dns.array" . | trim}}"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
      - {{ template "logstash.dns" . }}
    secretName: logstash-secret-{{ .Values.logstash.beats.pipelines_group_name }}
  rules:
    - host: {{ template "logstash.dns" . }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: logstash-{{ .Values.logstash.beats.pipelines_group_name }}-ls-api
                port:
                  number: 9600
---
{{ $concatUrl :=  (include "logstash.dns"  .) }}
{{ $prefix := (default "l" .Values.logstash.urlPrefix) }}
{{- range $index_i :=  until (.Values.logstash.count_beats |int ) -}}
{{- printf "\n"}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: tcp-services-{{ $.Values.logstash.beats.pipelines_group_name }}-{{$index_i}}
data:
  5044: "observability/logstash-{{ $.Values.logstash.beats.pipelines_group_name }}-ls-{{$index_i}}:5044"
---
{{- end }}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: logstash-{{ .Values.logstash.beats.pipelines_group_name }}
spec:
  duration: {{ .Values.logstash.cert.duration }}
  renewBefore: {{ .Values.logstash.cert.renewBefore }}
  commonName: "logstash-{{ .Values.logstash.beats.pipelines_group_name }}-ls-api.{{ .Release.Namespace }}.svc.cluster.local"
  secretName: logstash-secret-{{ .Values.logstash.beats.pipelines_group_name }}
  dnsNames:
    - "{{ template "logstash.dns" . }}"
{{- range $index_i :=  until (.Values.logstash.count_beats |int ) }}
    - "{{$prefix}}{{$index_i}}.{{$concatUrl}}"
{{- end }}    
    - "logstash.{{ .Release.Namespace }}" 
    - "logstash.{{ .Values.logstash.beats.pipelines_group_name }}-ls-api.{{ .Values.namespaceTag }}.{{ .Values.domainSuffix }}"
    - "logstash-{{ .Values.logstash.beats.pipelines_group_name }}-ls-api.{{ .Release.Namespace }}"
    - "logstash-{{ .Values.logstash.beats.pipelines_group_name }}-ls-api.{{ .Release.Namespace }}.svc.cluster.local"
  issuerRef:
    name: elk-clusterissuer-{{ .Release.Namespace }}
    kind: ClusterIssuer
  privateKey:
    encoding: "PKCS8" 
---
{{- end }}