{{- if eq .Values.namespaceTag .Values.mainNamespace }}
{{- if gt (.Values.logstash.count_syslog |int) 0}}
apiVersion: logstash.k8s.elastic.co/v1alpha1
kind: Logstash
metadata:
  name: logstash-syslog
  labels:
    app: logstash
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  image: {{ .Values.logstash.image }}:{{ default .Values.elasticVersion  .Values.logstash.imageTag }}
  version: {{ .Values.elasticVersion }}
  count: {{ .Values.logstash.count_syslog }}
  elasticsearchRefs:
  - name: {{ .Release.Name }}-elasticsearch
    clusterName: {{ .Release.Name }}-elasticsearch
  monitoring:
    logs:
      elasticsearchRefs:
        - name: {{ .Release.Name }}-elasticsearch    
  volumeClaimTemplates:
    - metadata:
        name: logstash-data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: {{ .Values.logstash.diskSpace }}
        storageClassName: {{ .Values.logstash.storageClassName }}
  services: 
{{- range $index :=  until (.Values.logstash.count_syslog |int ) -}}
{{- printf "\n"}}  
    - name: syslog-{{$index}}
      service:
        spec:
          ports:
          - port: 514
            name: {{ $.Values.logstash.syslog.pipelines_group_name }}
            protocol: TCP
          selector:
            statefulset.kubernetes.io/pod-name: logstash-syslog-ls-{{$index}}
{{- end}}
  config: 
    {{- with .Values.logstash.config }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  podTemplate:
    metadata:
      labels:
        stack-namespace: {{ .Release.Namespace }} 
    spec:
      containers:
      - name: logstash
        {{- with .Values.logstash.resources }}
        resources:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        volumeMounts:
        {{- range .Values.logstash.syslog.pipelines }}
        - name: pipeline-config-{{- .name }}
          mountPath: /app/elastic/logstash/config/pipelines/{{- .name -}}.config
          subPath: {{ .name -}}.config
        {{- end }}
        env:
          - name: LOGSTASH_USER
            valueFrom:
              secretKeyRef:
                name: logstash-writer-secret
                key: username
          - name: LOGSTASH_PASSWORD
            valueFrom:
              secretKeyRef:
                name: logstash-writer-secret
                key: password 
          - name: ELASTIC_ELASTICSEARCH_ES_HOSTS
            value: 'https://{{ .Release.Name }}-elasticsearch-es-http.{{ .Release.Namespace }}.svc:9200'
      volumes:
      {{- range .Values.logstash.syslog.pipelines }}
      - name: pipeline-config-{{- .name }}
        configMap:
          name: logstash-{{- $.Values.logstash.syslog.pipelines_group_name -}}-{{- .name -}}-config
          defaultMode: 511
      {{- end }}
  pipelinesRef:
    secretName: logstash-{{ .Values.logstash.syslog.pipelines_group_name }}-pipelines-yml
---
apiVersion: v1
kind: Secret
metadata:
  name: logstash-{{ .Values.logstash.syslog.pipelines_group_name }}-pipelines-yml
data:
  pipelines.yml: |
   {{ tpl .Values.logstash.pipelines_yml_config $ | nindent 6 | b64enc }}
---
{{- range .Values.logstash.syslog.pipelines }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-{{ $.Values.logstash.syslog.pipelines_group_name }}-{{ .name }}-config
data:
  {{ .name }}.config: |
    {{ tpl .input  $ | nindent 6 }}
    {{ tpl .filter $ | nindent 6 }}
    {{ tpl .output $ | nindent 6 }} 
---
{{- end }}
{{- end }}
{{- end }}