apiVersion: beat.k8s.elastic.co/v1beta1
kind: Beat
metadata:
  name: metricbeat-hpa
  labels:
    app: metricbeat
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  type: metricbeat
  version: {{ .Values.elasticVersion }}
  config:
    metricbeat:
      modules:
      - module: http
        metricsets: ["json"]
        period: 15s
        hosts: ["https://kubernetes.default.svc"]
        path: "/apis/autoscaling/v2/namespaces/{{ .Release.Namespace }}/horizontalpodautoscalers"
        namespace: "kubernetes_hpa"
        bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
        ssl:
          verification_mode: none
        json:
          keys_under_root: false
          add_error_key: true
    setup.ilm.enabled: true
    setup.ilm.policy_name: metricbeat-hpa-ilm
    setup.ilm.overwrite: true
    setup.ilm.policy_file: "/usr/share/metricbeat/ilm/metricbeat-hpa-ilm.json"
    processors:
      - script:
          lang: javascript
          source: >
            function process(event) {
              var hpaItems = event.Get("http.kubernetes_hpa.items");
              if (hpaItems && Array.isArray(hpaItems)) {
                hpaItems.forEach(function(item) {
                  if (item.metadata && item.metadata.managedFields) {
                    delete item.metadata.managedFields;  
                  }
                });
              }
            }
    output:
      logstash:
        hosts: ["${LOGSTASH_HOSTS}"]
        ssl.enabled: true
        ssl.certificate_authorities: ["/usr/share/metricbeat/certs/ca.crt"]
        ssl.verification_mode: full
        ssl.certificate: "/usr/share/metricbeat/certs/tls.crt"
        ssl.key: "/usr/share/metricbeat/certs/tls.key"
  deployment:
    replicas: 1
    podTemplate:
      spec:
        serviceAccountName: metricbeat-hpa
        automountServiceAccountToken: true
        securityContext:
          runAsUser: 0
        {{- if eq .Values.namespaceTag .Values.mainNamespace }}
          env:
            - name: RELEASE_NAME
              value: {{ .Release.Name }}
            - name: ELASTIC_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-elasticsearch-es-elastic-user 
                  key: elastic
        {{- end }}
        containers:
        - name: metricbeat
          args:
            - -e
            - -c
            - /etc/beat.yml
          {{- with .Values.metricbeat_hpa.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts: 
          - mountPath: /usr/share/metricbeat/certs
            name: metricbeat-hpa-certs
          env:
            - name: LOGSTASH_HOSTS
              value: 'logstash-mon-ls-hpa.{{ .Values.mainNamespace }}.svc.cluster.local:5044'
        volumes:    
        - name: metricbeat-hpa-certs
          secret:
            secretName: metricbeat-hpa-certs-secret-{{ .Release.Namespace }}
        - name: repo
          emptyDir: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: metricbeat-hpa-certificate-{{ .Release.Namespace }}
spec:
  secretName: metricbeat-hpa-certs-secret-{{ .Release.Namespace }}
  duration: {{ .Values.metricbeat_hpa.cert.duration }}
  renewBefore: {{ .Values.metricbeat_hpa.cert.renewBefore }}
  commonName: {{ template "metricbeat_hpa.dns" . }}
  dnsNames:
    - "{{ template "metricbeat_hpa.dns" . }}"
  issuerRef:
    name: elk-clusterissuer-{{ .Values.mainNamespace }}
    kind: ClusterIssuer
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: metricbeat-hpa-{{ .Release.Namespace }}
rules:
- apiGroups:
  - autoscaling
  resources:
  - horizontalpodautoscalers
  verbs:
  - get
  - list
  - watch
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: metricbeat-hpa
  namespace: {{.Release.Namespace}} 
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: metricbeat-hpa-{{ .Release.Namespace }}
subjects:
- kind: ServiceAccount
  name: metricbeat-hpa
  namespace: {{.Release.Namespace}} 
roleRef:
  kind: ClusterRole
  name: metricbeat-hpa-{{ .Release.Namespace }}
  apiGroup: rbac.authorization.k8s.io
---