{{- if eq .Values.namespaceTag .Values.mainNamespace }}
apiVersion: batch/v1
kind: Job
metadata:
  name: objects-loader
  labels:
    app: objects-loader
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
    argocd.argoproj.io/sync-wave: "1"
spec:
  backoffLimit: 3
  ttlSecondsAfterFinished: 3600
  template:
    spec:
      restartPolicy: OnFailure
      volumes:
        - name: load-objects-script
          configMap:
            name: load-objects-script
            defaultMode: 0755
        - name: ilm-temp
          emptyDir: {}
        - name: apm-ilms
          configMap:
            name: apm-ilms-configmap
        - name: metricbeat-ilm-vol
          configMap:
            name: metricbeat-ilm-configmap
        - name: filebeat-ilm-vol
          configMap:
            name: filebeat-ilm-configmap
        - name: heartbeat-ilm-vol
          configMap:
            name: heartbeat-ilm-configmap
        - name: logstash-monitoring-ilm-vol
          configMap:
            name: logstash-monitoring-ilm-configmap
        - name: logstash-beats-ilms-vol
          configMap:
            name: logstash-beats-ilms-configmap
        - name: templates-vol
          configMap:
            name: templates-configmap
      containers:
        - name: objects-loader
          image: alpine/git:latest
          command: ["/bin/sh", "-c", "apk add --no-cache curl gawk coreutils bash && /bin/bash /scripts/load_objects.sh 2>&1"]
          env:
            - name: RELEASE_NAME
              value: {{ .Release.Name }}
            - name: ELASTIC_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-elasticsearch-es-elastic-user
                  key: elastic
            - name: STACK_VERSION
              value: {{ .Values.elasticVersion }}
          volumeMounts:
            - name: load-objects-script
              mountPath: /scripts
            - name: ilm-temp
              mountPath: /mnt/ilm
            - name: apm-ilms
              mountPath: /usr/share/apm-server/ilm
            - name: metricbeat-ilm-vol
              mountPath: /usr/share/metricbeat/ilm
            - name: filebeat-ilm-vol
              mountPath: /usr/share/filebeat/ilm/filebeat-ilm.json
              subPath: filebeat-ilm.json
            - name: heartbeat-ilm-vol
              mountPath: /usr/share/heartbeat/ilm/heartbeat-ilm.json
              subPath: heartbeat-ilm.json
            - name: logstash-monitoring-ilm-vol
              mountPath: /usr/share/logstash-mon/ilm/logstash-monitoring-ilm.json
              subPath: logstash-monitoring-ilm.json
            - name: logstash-beats-ilms-vol
              mountPath: /usr/share/logstash-beats/ilm
            - name: templates-vol
              mountPath: /mnt/templates
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: load-objects-script
data:
  load_objects.sh: |
{{ .Files.Get "kibana/scripts/load_objects.sh" | indent 4 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: apm-ilms-configmap
data: 
  metrics-apm.app_metrics-default_policy.json: |
    {
      "policy": {
        "phases": {
        {{- if eq .Values.deploy_minimal_stack true }}
          "hot": {
            "actions": {
              "rollover": {
                "max_age": "{{ .Values.apmServer.minimal_stack_ilm.hot.max_age }}",
                "max_primary_shard_size": "{{ .Values.apmServer.minimal_stack_ilm.hot.max_primary_shard_size }}"
              },
              "set_priority": {
                "priority": 100
              }
            },
            "min_age": "0ms"
          },
          "delete": {
            "min_age": "{{ .Values.apmServer.minimal_stack_ilm.delete.min_age }}",
            "actions": {
              "delete": {}
            }
          }
        }
        {{- else }}
          "hot": {
            "actions": {
              "rollover": {
                "max_age": "{{ .Values.apmServer.ilm.hot.max_age }}",
                "max_primary_shard_size": "{{ .Values.apmServer.ilm.hot.max_primary_shard_size }}"
              },
              "set_priority": {
                "priority": 100
              }
            },
            "min_age": "0ms"
          },
          "delete": {
            "min_age": "{{ .Values.apmServer.ilm.delete.min_age }}",
            "actions": {
              "delete": {}
            }
          }
        }
        {{- end }}
        
      }
    }
  traces-apm.traces-default_policy.json: |
    {
      "policy": {
        "phases": {
        {{- if eq .Values.deploy_minimal_stack true }}
          "hot": {
            "actions": {
              "rollover": {
                "max_age": "{{ .Values.apmServer.minimal_stack_ilm.hot.max_age }}",
                "max_primary_shard_size": "{{ .Values.apmServer.minimal_stack_ilm.hot.max_primary_shard_size }}"
              },
              "set_priority": {
                "priority": 100
              }
            },
            "min_age": "0ms"
          },
          "delete": {
            "min_age": "{{ .Values.apmServer.minimal_stack_ilm.delete.min_age }}",
            "actions": {
              "delete": {}
            }
          }
        }
        {{- else }}
          "hot": {
            "actions": {
              "rollover": {
                "max_age": "{{ .Values.apmServer.ilm.hot.max_age }}",
                "max_primary_shard_size": "{{ .Values.apmServer.ilm.hot.max_primary_shard_size }}"
              },
              "set_priority": {
                "priority": 100
              }
            },
            "min_age": "0ms"
          },
          "delete": {
            "min_age": "{{ .Values.apmServer.ilm.delete.min_age }}",
            "actions": {
              "delete": {}
            }
          }
          }
        {{- end }}
        
      }
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: metricbeat-ilm-configmap
data: 
  metricbeat-ilm.json: |
    {
      "policy": {
        "phases": {
        {{- if eq .Values.deploy_minimal_stack true }}

          "hot": {
            "actions": {
              "rollover": {
                "max_age": "{{ .Values.metricbeat.minimal_stack_ilm.hot.max_age }}",
                "max_primary_shard_size": "{{ .Values.metricbeat.minimal_stack_ilm.hot.max_primary_shard_size }}"
              },
              "set_priority": {
                "priority": 100
              }
            },
            "min_age": "0ms"
          },
          "delete": {
            "min_age":  "{{ .Values.metricbeat.minimal_stack_ilm.delete.min_age }}",
            "actions": {
              "delete": {}
            }
          }
        }
        {{- else }}
          "hot": {
            "actions": {
              "rollover": {
                "max_age": "{{ .Values.metricbeat.ilm.hot.max_age }}",
                "max_primary_shard_size": "{{ .Values.metricbeat.ilm.hot.max_primary_shard_size }}"
              },
              "set_priority": {
                "priority": 100
              }
            },
            "min_age": "0ms"
          },
          "delete": {
            "min_age":  "{{ .Values.metricbeat.ilm.delete.min_age }}",
            "actions": {
              "delete": {}
            }
          }
        }
        {{- end }}
      }
    }
  metricbeat-hpa-ilm.json: |
    {
      "policy": {
        "phases": {
        {{- if eq .Values.deploy_minimal_stack true }}

          "hot": {
            "actions": {
              "rollover": {
                "max_age": "{{ .Values.metricbeat_hpa.minimal_stack_ilm.hot.max_age }}",
                "max_primary_shard_size": "{{ .Values.metricbeat_hpa.minimal_stack_ilm.hot.max_primary_shard_size }}"
              },
              "set_priority": {
                "priority": 100
              }
            },
            "min_age": "0ms"
          },
          "delete": {
            "min_age":  "{{ .Values.metricbeat_hpa.minimal_stack_ilm.delete.min_age }}",
            "actions": {
              "delete": {}
            }
          }
        }
        {{- else }}
          "hot": {
            "actions": {
              "rollover": {
                "max_age": "{{ .Values.metricbeat_hpa.ilm.hot.max_age }}",
                "max_primary_shard_size": "{{ .Values.metricbeat_hpa.ilm.hot.max_primary_shard_size }}"
              },
              "set_priority": {
                "priority": 100
              }
            },
            "min_age": "0ms"
          },
          "delete": {
            "min_age":  "{{ .Values.metricbeat_hpa.ilm.delete.min_age }}",
            "actions": {
              "delete": {}
            }
          }
        }
        {{- end }}
      }
    }
--- 
apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-monitoring-ilm-configmap
data: 
  logstash-monitoring-ilm.json: |
    {
      "policy": {
        "phases": {
        {{- if eq .Values.deploy_minimal_stack true }}
          "hot": {
            "actions": {
              "rollover": {
                "max_age": "{{ .Values.filebeat.minimal_stack_ilm.hot.max_age }}",
                "max_primary_shard_size": "{{ .Values.filebeat.minimal_stack_ilm.hot.max_primary_shard_size }}"
              },
              "set_priority": {
                "priority": 100
              }
            },
            "min_age": "0ms"
          },
          "delete": {
            "min_age":  "{{ .Values.filebeat.minimal_stack_ilm.delete.min_age }}",
            "actions": {
              "delete": {}
            }
          }
        }
        {{- else }}
          "hot": {
            "actions": {
              "rollover": {
                "max_age": "{{ .Values.filebeat.ilm.hot.max_age }}",
                "max_primary_shard_size": "{{ .Values.filebeat.ilm.hot.max_primary_shard_size }}"
              },
              "set_priority": {
                "priority": 100
              }
            },
            "min_age": "0ms"
          },
          "delete": {
            "min_age":  "{{ .Values.filebeat.ilm.delete.min_age }}",
            "actions": {
              "delete": {}
            }
          }
        }
        {{- end }}
      }
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-beats-ilms-configmap
data: 
  business-ilm.json: |
    {
      "policy": {
        "phases": {
        {{- if eq .Values.deploy_minimal_stack true }}
          "hot": {
            "actions": {
              "rollover": {
                "max_age": "{{ .Values.logstash.minimal_stack_ilm.business.hot.max_age }}",
                "max_primary_shard_size": "{{ .Values.logstash.minimal_stack_ilm.business.hot.max_primary_shard_size }}"
              },
              "set_priority": {
                "priority": 100
              }
            },
            "min_age": "0ms"
          },
          "delete": {
            "min_age":  "{{ .Values.logstash.minimal_stack_ilm.business.delete.min_age }}",
            "actions": {
              "delete": {}
            }
          }
        }
        {{- else }}
          "hot": {
            "actions": {
              "rollover": {
                "max_age": "{{ .Values.logstash.ilm.business.hot.max_age }}",
                "max_primary_shard_size": "{{ .Values.logstash.ilm.business.hot.max_primary_shard_size }}"
              },
              "set_priority": {
                "priority": 100
              }
            },
            "min_age": "0ms"
          },
          "delete": {
            "min_age":  "{{ .Values.logstash.ilm.business.delete.min_age }}",
            "actions": {
              "delete": {}
            }
          }
        }
        {{- end }}
      }
    }
  technical-ilm.json: |
    {
      "policy": {
        "phases": {
        {{- if eq .Values.deploy_minimal_stack true }}
          "hot": {
            "actions": {
              "rollover": {
                "max_age": "{{ .Values.logstash.minimal_stack_ilm.technical.hot.max_age }}",
                "max_primary_shard_size": "{{ .Values.logstash.minimal_stack_ilm.technical.hot.max_primary_shard_size }}"
              },
              "set_priority": {
                "priority": 100
              }
            },
            "min_age": "0ms"
          },
          "delete": {
            "min_age":  "{{ .Values.logstash.minimal_stack_ilm.technical.delete.min_age }}",
            "actions": {
              "delete": {}
            }
          }
        }
        {{- else }}
          "hot": {
            "actions": {
              "rollover": {
                "max_age": "{{ .Values.logstash.ilm.technical.hot.max_age }}",
                "max_primary_shard_size": "{{ .Values.logstash.ilm.technical.hot.max_primary_shard_size }}"
              },
              "set_priority": {
                "priority": 100
              }
            },
            "min_age": "0ms"
          },
          "delete": {
            "min_age":  "{{ .Values.logstash.ilm.technical.delete.min_age }}",
            "actions": {
              "delete": {}
            }
          }
        }
        {{- end }}
      }
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: heartbeat-ilm-configmap
data: 
  heartbeat-ilm.json: |
    {
      "policy": {
        "phases": {
        {{- if eq .Values.deploy_minimal_stack true }}
          "hot": {
            "actions": {
              "rollover": {
                "max_age": "{{ .Values.heartbeat.minimal_stack_ilm.hot.max_age }}",
                "max_primary_shard_size": "{{ .Values.heartbeat.minimal_stack_ilm.hot.max_primary_shard_size }}"
              },
              "set_priority": {
                "priority": 100
              }
            },
            "min_age": "0ms"
          },
          "delete": {
            "min_age":  "{{ .Values.heartbeat.minimal_stack_ilm.delete.min_age }}",
            "actions": {
              "delete": {}
            }
          }
        }
        {{- else }}
          "hot": {
            "actions": {
              "rollover": {
                "max_age": "{{ .Values.heartbeat.ilm.hot.max_age }}",
                "max_primary_shard_size": "{{ .Values.heartbeat.ilm.hot.max_primary_shard_size }}"
              },
              "set_priority": {
                "priority": 100
              }
            },
            "min_age": "0ms"
          },
          "delete": {
            "min_age":  "{{ .Values.heartbeat.ilm.delete.min_age }}",
            "actions": {
              "delete": {}
            }
          }
        }
        {{- end }}
      }
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-ilm-configmap
data: 
  filebeat-ilm.json: |
    {
      "policy": {
        "phases": {
        {{- if eq .Values.deploy_minimal_stack true }}
          "hot": {
            "actions": {
              "rollover": {
                "max_age": "{{ .Values.filebeat.minimal_stack_ilm.hot.max_age }}",
                "max_primary_shard_size": "{{ .Values.filebeat.minimal_stack_ilm.hot.max_primary_shard_size }}"
              },
              "set_priority": {
                "priority": 100
              }
            },
            "min_age": "0ms"
          },
          "delete": {
            "min_age":  "{{ .Values.filebeat.minimal_stack_ilm.delete.min_age }}",
            "actions": {
              "delete": {}
            }
          }
        }
        {{- else }}
          "hot": {
            "actions": {
              "rollover": {
                "max_age": "{{ .Values.filebeat.ilm.hot.max_age }}",
                "max_primary_shard_size": "{{ .Values.filebeat.ilm.hot.max_primary_shard_size }}"
              },
              "set_priority": {
                "priority": 100
              }
            },
            "min_age": "0ms"
          },
          "delete": {
            "min_age":  "{{ .Values.filebeat.ilm.delete.min_age }}",
            "actions": {
              "delete": {}
            }
          }
        }
        {{- end }}
      }
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: templates-configmap
data: 
  business-template-log.json: |
{{ .Files.Get "kibana/templates/business-template-log.json" | indent 4 }}
  technical-template-log.json: |
{{ .Files.Get "kibana/templates/technical-template-log.json" | indent 4 }}
  metricbeat-hpa-template-log.json: |
{{ .Files.Get "kibana/templates/metricbeat-hpa-template-log.json" | indent 4 }}
  filebeat-monitoring-template-log.json: |
{{ .Files.Get "kibana/templates/filebeat-monitoring-template-log.json" | indent 4 }}
  metricbeat-template-log.json: |
{{ .Files.Get "kibana/templates/metricbeat-template-log.json" | indent 4 }}
{{- end }}