{{- if eq .Values.namespaceTag .Values.mainNamespace }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: otel-collector
  namespace: {{ .Release.Namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  {{- if eq .Values.deploy_minimal_stack true }}
  replicas: {{ .Values.otel_collector.minimal_stack_count }}
  {{- else }}
  replicas: {{ .Values.otel_collector.count }}
  {{- end }}
  selector:
    matchLabels:
      app: otel-collector
  template:
    metadata:
      labels:
        app: otel-collector
    spec:
      containers:
        - name: opentelemetry-collector
          {{- if eq .Values.deploy_minimal_stack true }}
          {{- with .Values.otel_collector.minimal_stack_resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- else }}
          {{- with .Values.otel_collector.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- end }}
          image: "otel/opentelemetry-collector-k8s:0.121.0"
          args:
            - --config=/conf/relay.yaml
          securityContext:
            {}
          ports:
            - name: otlp
              containerPort: 4317
              protocol: TCP
            - name: otlp-http
              containerPort: 4318
              protocol: TCP

          env:
            - name: BEARER_TOKEN
              valueFrom:
                secretKeyRef:
                  name: apm-server-apm-token
                  key: secret-token


          volumeMounts:
            - name: opentelemetry-collector-configmap
              mountPath: /conf
      volumes:
        - name: opentelemetry-collector-configmap
          configMap:
            name: opentelemetry-collector
            items:
              - key: relay
                path: relay.yaml
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: opentelemetry-collector
data:
  relay: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: "0.0.0.0:4317"
          http:
            endpoint: "0.0.0.0:4318"
    processors:
      batch:
    exporters:
      otlphttp:
        endpoint: "https://apm.{{ .Values.mainNamespace }}.{{ .Values.domainSuffix }}"
        #Need to add CA
        headers:
          Authorization: Bearer ${env:BEARER_TOKEN}
        tls:
          insecure: true
    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [otlphttp]
        metrics:
          receivers: [otlp]  
          processors: [batch]
          exporters: [otlphttp]
---
apiVersion: v1
kind: Service
metadata:
  name: otel-collector
spec:
  type: ClusterIP
  ports:
    - name: otpl-grpc
      port: 4317
      targetPort: 4317
    - name: otlp-http
      port: 4318
      targetPort: 4318
  selector:
    app: otel-collector
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-otel-collector
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    #cert-manager.io/cluster-issuer: {{ .Values.clusterIssuer }}
spec:
  ingressClassName: nginx
  #tls:
  #- hosts:
  #    - {{ template "collector.dns" . }}
  #  secretName: {{ .Release.Name }}-collector-ssl
  rules:
    - host: {{ template "collector.dns" . }}
      http:
        paths:
          - path: "/"
            pathType: Prefix
            backend: 
              service:
                name:  otel-collector
                port:
                  number: 4318
{{- end }}