replicaCount: 1

image:
  repository: registry.code.europa.eu/simpl/simpl-open/development/data1/simpl-files
  pullPolicy: IfNotPresent
  tag: 1.2.3

service:
  type: ClusterIP
  port: 80

resources:
  limits:
    cpu: "500m"
    memory: "512Mi"
  requests:
    cpu: "200m"
    memory: "128Mi"

ingress:
  hostname: files.dev.simpl-europe.eu
  secretName: simpl-tls-files
  clusterIssuer: dev-prod
  ingressClass: nginx
