apiVersion: v1
kind: Secret
metadata:
    name: kafka-secret
type: Opaque
data:
    username: {{ .Values.secrets.kafka.username | b64enc }}
    password: {{ .Values.secrets.kafka.password | b64enc }}
{{- if not (lookup "v1" "Secret" .Release.Namespace "gitea-secret") }}
---
apiVersion: v1
kind: Secret
metadata:
    name: gitea-secret
type: Opaque
data:
    username: {{ .Values.secrets.gitea.username | b64enc }}
    password: {{ .Values.secrets.gitea.password | b64enc }}
{{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: eso-sa
  annotations:
    kubernetes.io/service-account.name: eso
type: kubernetes.io/service-account-token

