apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ template "app.name" . }}"
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
    app.kubernetes.io/instance: {{ include "app.revision" . }}
    app.kubernetes.io/part-of: rse
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      {{- include "app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "app.labels" . | nindent 8 }}
      annotations:
        {{- include "app.metricsAnnotations" . | nindent 8 }}
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: {{ .Values.hashicorp.role }}
        {{- if and (hasKey .Values "hashicorp") (hasKey .Values.hashicorp "service") }}
        vault.hashicorp.com/service: {{ .Values.hashicorp.service }}
        {{- end }}
        vault.hashicorp.com/agent-inject-secret-config.txt: "{{ tpl .Values.secretConfigPath . }}"
        vault.hashicorp.com/agent-inject-template-config.txt: |
          {{- $secretPath := tpl .Values.secretConfigPath . -}}
          {{- $template := printf (printf "{{`{{ with secret \"%s\" }}\n" $secretPath) -}}
          {{- $template = printf "%s{{ range $k, $v := .Data.data }}\n" $template -}}
          {{- $template = printf "%s  export {{ $k }}={{ $v }}\n" $template -}}
          {{- $template = printf "%s{{ end }}\n" $template -}}
          {{- $template = printf "%s{{ end }}`}}" $template -}}
          {{- tpl $template . | nindent 10 }}

{{- if .Values.podAnnotations }}
{{ toYaml .Values.podAnnotations | indent 8 }}
{{- end }}
    spec:
      automountServiceAccountToken: {{ .Values.serviceAccount.automountServiceAccountToken | default false }}
      serviceAccountName: {{ .Values.serviceAccount.name | default .Release.Namespace }}
      securityContext:
{{- include "app.securitycontext" . | nindent 8 }}
      {{- if $.Values.image.pullSecrets }}
      imagePullSecrets:
        - name: {{ .Values.image.pullSecrets }}
      {{- end }}
      containers:
      - name: {{ template "app.name" . }}
        image: "code.europa.eu:4567/simpl/simpl-open/development/gaia-x-edc/poc-gaia-edc/signer:0.0.1"
        imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
        command: [ "/bin/sh" ]
        args: [ "-c", ". /vault/secrets/config.txt && cd /opt && ./signer" ]
        ports:
        {{- if .Values.metrics.enabled }}
          - name: monitoring
            containerPort: {{ .Values.metrics.port }}
        {{- end }}
          - name: http
            containerPort: {{ .Values.signer.http.port }}
        {{- with .Values.env }}
        env:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        readinessProbe:
          httpGet:
            path: /readiness
            port: {{ .Values.signer.http.port }}
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 2
          failureThreshold: 2
          timeoutSeconds: 5
        resources:
{{ toYaml .Values.resources | indent 10 }}
