apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: eso-cloud-accounts
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: http://{{ .Values.giteaUrl }}/{{ .Values.secrets.gitea.username }}/eso-repo.git
    path: cloud-accounts
    targetRevision: master
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
      allowEmpty: true
