apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: terraform-manager
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: http://{{ .Values.giteaUrl }}/{{ .Values.secrets.gitea.username }}/management-repo.git
    path: terraform-fluxcd-runners
    targetRevision: master
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
      allowEmpty: true