{{- if .Values.kafka.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ include "infra-backend.fullname" . }}-zookeeper
  labels:
    app: {{ .Chart.Name }}
spec:
  replicas: {{ .Values.zookeeper.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
        - name: zookeeper
          image: "{{ .Values.zookeeper.image.repository }}:{{ .Values.zookeeper.image.tag }}"
          imagePullPolicy: {{ .Values.zookeeper.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.zookeeper.service.clientPort }}
            - containerPort: {{ .Values.zookeeper.service.quorumPort }}
            - containerPort: {{ .Values.zookeeper.service.electionPort }}
          env:
            - name: ZOOKEEPER_TICK_TIME
              value: "{{ .Values.zookeeper.zookeeperConfig.tickTime }}"
            - name: ZOOKEEPER_INIT_LIMIT
              value: "{{ .Values.zookeeper.zookeeperConfig.initLimit }}"
            - name: ZOOKEEPER_SYNC_LIMIT
              value: "{{ .Values.zookeeper.zookeeperConfig.syncLimit }}"
            - name: ZOOKEEPER_CLIENT_PORT
              value: "{{ .Values.zookeeper.zookeeperConfig.clientPort }}"
          volumeMounts:
            - name: data
              mountPath: "{{ .Values.zookeeper.zookeeperConfig.dataDir }}"
          resources:
            limits:
              memory: "{{ .Values.zookeeper.resources.limits.memory }}"
              cpu: "{{ .Values.zookeeper.resources.limits.cpu }}"
            requests:
              memory: "{{ .Values.zookeeper.resources.requests.memory }}"
              cpu: "{{ .Values.zookeeper.resources.requests.cpu }}"
      volumes:
        - name: data
          emptyDir: {}
{{- end }}          