apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: view-application
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups:
      - argoproj.io
    resources:
      - applications
    verbs:
      - list
      - get
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: patch-application
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups:
      - argoproj.io
    resources:
      - applications
    verbs:
      - patch
      - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: view-workflow
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups:
      - argoproj.io
    resources:
      - workflows
      - workflowtaskresults
    verbs:
      - list
      - get
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: patch-workflow
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups:
      - argoproj.io
    resources:
      - workflows
      - workflowtaskresults
    verbs:
      - patch
      - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: view-terraform
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups:
      - infra.contrib.fluxcd.io
    resources:
      - terraforms
    verbs:
      - list
      - get
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: patch-terraform
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups:
      - infra.contrib.fluxcd.io
    resources:
      - terraforms
    verbs:
      - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: view-terraform-infrastructure-secrets
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: view-eso
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups:
      - external-secrets.io
    resources:
      - externalsecrets
    verbs:
      - list
      - get
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: patch-eso
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups:
      - external-secrets.io
    resources:
      - externalsecrets
    verbs:
      - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: view-application
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: view-application
subjects:
- kind: ServiceAccount
  name: observer
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: view-eso
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: view-eso
subjects:
  - kind: ServiceAccount
    name: observer
    namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: patch-eso
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: patch-eso
subjects:
  - kind: ServiceAccount
    name: observer
    namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: patch-application
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: patch-application
subjects:
- kind: ServiceAccount
  name: observer
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: view-workflow
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: view-workflow
subjects:
- kind: ServiceAccount
  name: observer
  namespace: {{ .Release.Namespace }}
- kind: ServiceAccount
  name: provisioner-events
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: patch-workflow
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: patch-workflow
subjects:
- kind: ServiceAccount
  name: provisioner-workflows
  namespace: {{ .Release.Namespace }}
- kind: ServiceAccount
  name: provisioner-events
  namespace: {{ .Release.Namespace }}
- kind: ServiceAccount
  name: observer
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: view-terraform-infrastructure-secrets
  namespace: {{ .Release.Namespace }}
subjects:
  - kind: ServiceAccount
    name: observer
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: view-terraform-infrastructure-secrets
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: view-terraform
  namespace: {{ .Release.Namespace }}
subjects:
  - kind: ServiceAccount
    name: observer
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: view-terraform
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: patch-terraform
  namespace: {{ .Release.Namespace }}
subjects:
  - kind: ServiceAccount
    name: observer
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: patch-terraform
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Release.Namespace }}-view-crossplane
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: crossplane-view
subjects:
  - kind: ServiceAccount
    name: observer
    namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: infrastructure-edit-crossplane
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: crossplane-edit
subjects:
  - kind: ServiceAccount
    name: observer
    namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: eso-vault-auth
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
  - kind: ServiceAccount
    name: eso
    namespace: {{ .Release.Namespace }}