apiVersion: v1
kind: ServiceAccount
metadata:
  name: provisioner-events
  namespace: {{ .Release.Namespace }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: provisioner-workflows
  namespace: {{ .Release.Namespace }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: observer
  namespace: {{ .Release.Namespace }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: eso
  namespace: {{ .Release.Namespace }}
