{{- $backend := .Values.backend | default dict }}
{{- $serviceAccount := $backend.serviceAccount | default dict }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $serviceAccount.name | default .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}
