gitea:
  storageClassName: #GITEA_STORAGE_CLASS
  volumeSize: #GITEA_VOLUME_SIZE

argo-cd:
  crds:
    install: true #ARGO_CD_CRDS_INSTALL

secrets:
  gitea:
    username: #GITEA_USERNAME
    password: #GITEA_PASSWORD
