deployment:
  image: "${CI_REGISTRY_IMAGE}"
  tag: 1.0.21

resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  limits:
    cpu: 250m
    memory: 1Gi
  requests:
    cpu: 250m
    memory: 1Gi


ingress:
  enabled: true
  apiPath: /api
  managementPath: /management
  protocolPath: /protocol
  publicPath: /public
  controlPath: /control
  clusterIssuer: dev-prod
  corsAllowOrigin: "*"

contractmanager:
  extension:
    enabled: false
  url: http://url:8080/contract/v1/

serviceAccount:
  enabled: true

hashicorp:
  role: "gaiax"
  service: "https://vault.tools.simpl-europe.eu/"

secretEngine: kv/gaia-x
secretConfigPath: "{{ .Values.secretEngine }}/{{ .Release.Namespace }}-simpl-edc"
