{{- if .Values.kafka.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ include "infra-backend.fullname" . }}-kafka-ui
  labels:
    app: kafka-ui
    release: {{ .Release.Name }}
spec:
  replicas: {{ .Values.kafkaUi.replicaCount }}
  selector:
    matchLabels:
      app: kafka-ui
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: kafka-ui
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: kafka-ui
          image: "{{ .Values.kafkaUi.image.repository }}:{{ .Values.kafkaUi.image.tag }}"
          imagePullPolicy: {{ .Values.kafkaUi.image.pullPolicy }}
          ports:
            - containerPort: 8080
          env:
            {{- range $index, $cluster := .Values.kafkaUi.kafkaClusters }}
            - name: "KAFKA_CLUSTERS_{{ $index }}_NAME"
              value: "{{ $cluster.name }}"
            - name: "KAFKA_CLUSTERS_{{ $index }}_BOOTSTRAPSERVERS"
              value: "{{ $cluster.bootstrapServers }}"
            - name: "KAFKA_CLUSTERS_{{ $index }}_METRICS_PORT"
              value: "{{ $cluster.metricsPort }}"
            - name: "KAFKA_CLUSTERS_{{ $index }}_DYNAMIC_CONFIG_ENABLED"
              value: "{{ $cluster.dynamicConfigEnabled }}"
            {{- end }}
      nodeSelector:
        {{- toYaml .Values.nodeSelector | nindent 8 }}
      tolerations:
        {{- toYaml .Values.tolerations | nindent 8 }}
      affinity:
        {{- toYaml .Values.affinity | nindent 8 }}
{{- end }}