apiVersion: v1
kind: Secret
metadata:
    name: gitea-secret
type: Opaque
data:
    username: {{ .Values.secrets.gitea.username | b64enc }}
    password: {{ .Values.secrets.gitea.password | b64enc }}
