{{- if .Values.kafka.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ include "infra-backend.fullname" . }}-kafka
  labels:
    app: {{ .Chart.Name }}
spec:
  replicas: {{ .Values.kafka.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
        - name: kafka
          image: "{{ .Values.kafka.image.repository }}:{{ .Values.kafka.image.tag }}"
          imagePullPolicy: {{ .Values.kafka.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.kafka.service.port }}
            - containerPort: {{ .Values.kafka.service.internalPort }}
            - containerPort: {{ .Values.kafka.service.jmxPort }}
          env:
            - name: KAFKA_BROKER_ID
              value: "{{ .Values.kafka.kafkaConfig.brokerId }}"
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: "{{ include "infra-backend.fullname" . }}-zookeeper-svc.{{ .Values.namespace }}.svc:{{ .Values.zookeeper.service.clientPort }}"
            - name: KAFKA_ADVERTISED_LISTENERS
              value: "PLAINTEXT://{{ include "infra-backend.fullname" . }}-kafka-svc.{{ .Values.namespace }}.svc:{{ .Values.kafka.service.internalPort }},PLAINTEXT_HOST://{{ include "infra-backend.fullname" . }}-kafka-svc.{{ .Values.namespace }}.svc:{{ .Values.kafka.service.port }}"
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: "{{ .Values.kafka.kafkaConfig.listenerSecurityProtocolMap }}"
            - name: KAFKA_AUTO_CREATE_TOPICS_ENABLE
              value: "{{ .Values.kafka.kafkaConfig.autoCreateTopicsEnable }}"
            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              value: "{{ .Values.kafka.kafkaConfig.offsetsTopicReplicationFactor }}"
            - name: KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR
              value: "{{ .Values.kafka.kafkaConfig.transactionStateLogReplicationFactor }}"
            - name: KAFKA_TRANSACTION_STATE_LOG_MIN_ISR
              value: "{{ .Values.kafka.kafkaConfig.transactionStateLogMinIsr }}"
            - name: KAFKA_MIN_INSYNC_REPLICAS
              value: "{{ .Values.kafka.kafkaConfig.minInsyncReplicas }}"
            - name: KAFKA_JMX_PORT
              value: "{{ .Values.kafka.kafkaConfig.jmxPort }}"            
          resources:
            limits:
              memory: "{{ .Values.kafka.resources.limits.memory }}"
              cpu: "{{ .Values.kafka.resources.limits.cpu }}"
            requests:
              memory: "{{ .Values.kafka.resources.requests.memory }}"
              cpu: "{{ .Values.kafka.resources.requests.cpu }}"
{{- end }}              