apiVersion: v2
name: dagster
description: "Local wrapper chart for Dagster, for ArgoCD"
type: application
version: 0.1.12
appVersion: 0.1.12

dependencies:
  - name: dagster
    version: 1.13.19
    repository: "https://dagster-io.github.io/helm"